//===- PropertyGen.cpp - Generate registered native property kinds -------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "mlir/TableGen/GenInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"

using namespace mlir;
using llvm::formatv;
using llvm::Record;
using llvm::RecordKeeper;

namespace {
struct RegisteredPropertyDef {
  StringRef cppNamespace;
  StringRef cppClass;
  StringRef mnemonic;
  StringRef storageType;
  StringRef verifier;
  StringRef hasher;
  StringRef parser;
  StringRef printer;
};

static SmallVector<RegisteredPropertyDef>
getRegisteredProperties(const RecordKeeper &records) {
  SmallVector<RegisteredPropertyDef> result;
  for (const Record *record : records.getAllDerivedDefinitions("PropDef")) {
    if (!record->getValueAsBit("generateWrapper"))
      continue;
    StringRef mnemonic = record->getValueAsString("mnemonic");
    StringRef cppNamespace = record->getValueAsString("cppNamespace");
    StringRef cppClass = record->getValueAsString("cppClass");
    if (mnemonic.empty() || cppNamespace.empty() || cppClass.empty())
      llvm::PrintFatalError(record->getLoc(),
                            "registered property requires a mnemonic, C++ "
                            "namespace, and class name");
    if (llvm::any_of(result, [&](const RegisteredPropertyDef &existing) {
          return existing.cppNamespace == cppNamespace &&
                 existing.cppClass == cppClass;
        }))
      llvm::PrintFatalError(record->getLoc(),
                            "two PropDef records define the same C++ kind");
    StringRef parser = record->getValueAsString("parser");
    StringRef printer = record->getValueAsString("printer");
    if (parser.empty() || printer.empty())
      llvm::PrintFatalError(record->getLoc(),
                            "registered property requires standalone parser "
                            "and printer bodies");
    // Multiple operation fields may specialize defaults and constraints while
    // using the same semantic kind. Emit its C++ wrapper only once.
    if (llvm::any_of(result, [&](const RegisteredPropertyDef &existing) {
          return existing.cppNamespace == cppNamespace &&
                 existing.cppClass == cppClass;
        }))
      continue;
    result.push_back({cppNamespace, cppClass, mnemonic,
                      record->getValueAsString("storageType"),
                      record->getValueAsString("verifier"),
                      record->getValueAsString("hasher"), parser, printer});
  }
  return result;
}

static bool emitPropertyDecls(const RecordKeeper &records, raw_ostream &os) {
  os << "// Generated by mlir-tblgen.\n";
  for (const RegisteredPropertyDef &property :
       getRegisteredProperties(records)) {
    os << formatv(
        "namespace {0} {{\n"
        "struct {1} {{\n"
        "  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID({1})\n"
        "  using StorageType = {2};\n"
        "  static constexpr llvm::StringLiteral name = \"{3}\";\n"
        "  static ::mlir::LogicalResult verify(const StorageType &value);\n",
        property.cppNamespace, property.cppClass, property.storageType,
        property.mnemonic);
    if (!property.hasher.empty())
      os << "  static ::llvm::hash_code hash(const StorageType &value);\n";
    os << "  static ::mlir::ParseResult parse(::mlir::AsmParser &parser, "
          "StorageType &value);\n"
          "  static void print(::mlir::AsmPrinter &printer, "
          "const StorageType &value);\n";
    os << "};\n} // namespace " << property.cppNamespace << "\n";
  }
  return false;
}

static bool emitPropertyDefs(const RecordKeeper &records, raw_ostream &os) {
  os << "// Generated by mlir-tblgen.\n";
  for (const RegisteredPropertyDef &property :
       getRegisteredProperties(records)) {
    os << formatv("::mlir::LogicalResult {0}::{1}::verify("
                  "const StorageType &value) {{\n",
                  property.cppNamespace, property.cppClass);
    if (property.verifier.empty())
      os << "  (void)value;\n  return ::mlir::success();\n";
    else
      os << property.verifier << "\n";
    os << "}\n";
    if (!property.hasher.empty()) {
      os << formatv("::llvm::hash_code {0}::{1}::hash("
                    "const StorageType &value) {{\n",
                    property.cppNamespace, property.cppClass);
      os << property.hasher << "\n}\n";
    }
    os << formatv("::mlir::ParseResult {0}::{1}::parse("
                  "::mlir::AsmParser &parser, StorageType &value) {{\n",
                  property.cppNamespace, property.cppClass);
    os << property.parser << "\n}\n";
    os << formatv("void {0}::{1}::print("
                  "::mlir::AsmPrinter &printer, const StorageType &value) {{\n",
                  property.cppNamespace, property.cppClass);
    os << property.printer << "\n}\n";
  }
  return false;
}
} // namespace

static mlir::GenRegistration
    genRegisteredPropertyDecls("gen-registered-property-decls",
                               "Generate registered property declarations",
                               &emitPropertyDecls);
static mlir::GenRegistration
    genRegisteredPropertyDefs("gen-registered-property-defs",
                              "Generate registered property definitions",
                              &emitPropertyDefs);
